public class Main {
    public static void main(String[] args) {
    var dog =  8.0;
    var cat = 3.6;
    var paper = 763789;
    System.out.println("Задача 1");
    System.out.println("Значение переменной dog = " + dog);
    System.out.println("Значение переменной cat = " + cat);
    System.out.println("Значение переменной paper = " + paper);
    System.out.println("Задача 2");
    dog = dog + 4;
    cat = cat + 4;
    paper = paper + 4;
    System.out.println(dog);
    System.out.println(cat);
    System.out.println(paper);
    System.out.println("Задача 3");
    dog = dog - 3.5;
    cat = cat - 1.6;
    paper = paper - 7639;
    System.out.println(dog);
    System.out.println(cat);
    System.out.println(paper);
    System.out.println("Задача 4");
    var friend = 19;
    System.out.println(friend);
    friend = friend + 2;
    System.out.println(friend);
    friend = friend / 7;
    System.out.println(friend);
    System.out.println("Задача 5");
    var frog = 3.5;
    System.out.println(frog);
    frog = frog * 10;
    System.out.println(frog);
    frog = frog / 3.5;
    System.out.println(frog);
    frog = frog + 4;
    System.out.println(frog);
    System.out.println("Задача 6");
    var oneBox = 78.2;
    var twoBox = 82.7;
    var totalMass = oneBox + twoBox;
    var massDifference = twoBox - oneBox;
    System.out.println("Разница между массами бойцов: " + massDifference + " кг");
    System.out.println("общая масса двух бойцов = " + totalMass+ "кг");
    System.out.println("Задача 7");
    var remainsBox = twoBox % oneBox;
    System.out.println("остаток от деления между двумя весами = " + remainsBox);
    System.out.println("Задача 8");
    var totalHours = 640;
    var hours = 8;
    var worker = totalHours / hours;
    System.out.println("Всего работников в компании — " + worker + " человек");
    var newWorker = worker + 94;
    var newTotalHours = newWorker * hours;
    System.out.println("Если в компании работает " + newWorker + " человек, то всего " + newTotalHours + " часов работы может быть проделено между сотрудниками");
    }
}